### PR TITLE
Update processor-add_kubernetes_metadata.asciidoc

### PR DESCRIPTION
**Pull request by gizas**
Update description for add_resource_metadata based on the https://github.com/elastic/beats/pull/36879 and the release notes since 8.11 https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-8.11.0.html

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]
LGTM!

**Review by tetianakravchenko — APPROVED** [review]

**Comment by gizas** [comment]
@kilfoyle seems that I dont have write access. Did something changed?

**Comment by kilfoyle** [comment]
@gizas I know the docs repos have been updated to tighten the security a bit. By "write access" do you mean you're unable to merge the PR? It shows as green for me so I'm happy to merge it.

CC @bmorelli25 just in case I'm missing something about the repo permissions.

**Comment by gizas** [comment]
@kilfoyle indeed I dont have access to merge the PR
See image below:

Screenshot 2023-11-21 at 9 46 24 AM

Please if you can merge it? Thank you very much

**Pull request merged**
