### PR TITLE
Move Agent policy settings docs to correct location

### PR DESCRIPTION
**Pull request by kilfoyle**
Some settings were missing or documented in the wrong location in the docs. This PR:

 - Moves the "Host name format" setting to the agent policy settings page, [here](https://ingest-docs_bk_1092.docs-preview.app.elstc.co/guide/en/fleet/master/agent-policy.html#fleet-agent-hostname-format-settings).
 - Adds the missing "Agent binary download" setting to the to the agent policy settings page, [here](https://ingest-docs_bk_1092.docs-preview.app.elstc.co/guide/en/fleet/master/agent-policy.html#agent-binary-download-settings).
 - Adds the missing "Proxy" setting to the Fleet Server settings page, [here](https://ingest-docs_bk_1092.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-settings.html#proxy-settings).

@juliaElastic, @criamico  The content isn't really new but rather just moved around. Would you mind taking a look just to make sure the docs are okay?

Closes: #1091

### CODE REVIEW

**Comment by kilfoyle** [comment]
@elasticmachine run docs-build

**Comment by kilfoyle** [comment]
Opened a [security docs PR](https://github.com/elastic/security-docs/pull/5463) to fix the failing docs CI check.

**Comment by kilfoyle** [comment]
@elasticmachine run docs-build

**Review by karenzone — APPROVED** [review]
LGTM

**Review by criamico — APPROVED** [review]
LGTM 🚢

**Pull request merged**
