### PR TITLE
Fix agent status docs for unhealthy status

### PR DESCRIPTION
**Pull request by kilfoyle**
This corrects the meaning of `Unhealthy` for Elastic Agent status, as documented in [View agent status overview](https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html#view-agent-status).

Closes: #1284

---

Screenshot 2024-09-04 at 2 21 32 PM

### CODE REVIEW

**Review by kpollich — COMMENTED** [review]
The new description looks great, but I think we also need to update the diagram to match: 

image

**Comment by nimarezainia** [comment]
> The new description looks great, but I think we also need to update the diagram to match:
> 
> image

yeah you are right, I'll redo this. It's a left over from before we had health reporting.

**Comment by kilfoyle** [comment]
@kpollich  I've added in the nice, new graphic:

---

Screenshot 2024-09-05 at 11 25 14 AM

**Review by kpollich — APPROVED** [review]
Thanks so much for taking care of this, and thanks @nimarezainia for helping with the diagram ❤️

**Review by florent-leborgne — APPROVED** [review]
LGTM!

**Pull request merged**
