### PR TITLE
Move with history

### PR DESCRIPTION
**Pull request by bmorelli25**
This PR moves the contents of [`elastic/observability-docs/docs/en/ingest-management`](https://github.com/elastic/observability-docs/tree/main/docs/en/ingest-management) to this repository while maintaining history.

Here's how:
```
cd observability-docs
git subtree split -P docs/en/ingest-management -b split

cd integration-docs
git checkout --orphan temp
git pull git@github.com:bmorelli25/observability-docs.git split
git checkout move-with-history -b
git merge --allow-unrelated-histories temp
```

### CODE REVIEW

**Comment by bmorelli25** [comment]
Command:

```
$GIT_HOME/docs/build_docs --doc $GIT_HOME/ingest-docs/docs/en/ingest-management/index.asciidoc --resource=$GIT_HOME/apm-server/docs --chunk 2
```

Doc build errors: 

```
INFO:build_docs:asciidoctor: ERROR: beats-agent-comparison.asciidoc: line 19: include file not found: /doc/ingest-docs/docs/en/ingest-management/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/install-elastic-agent.asciidoc: line 27: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/install-standalone-elastic-agent.asciidoc: line 5: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/install-standalone-elastic-agent.asciidoc: line 32: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/tab-widgets/download-widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/install-standalone-elastic-agent.asciidoc: line 81: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/tab-widgets/run-standalone-widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/upgrade-standalone-elastic-agent.asciidoc: line 4: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/elastic-agent-container.asciidoc: line 21: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/shared/spin-up-the-stack/widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/elastic-agent-container.asciidoc: line 59: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/tab-widgets/run-agent-image/widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/run-container-common/kibana-fleet-data.asciidoc: line 4: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/run-container-common/{observability-docs-root}/docs/en/shared/open-kibana/widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc: line 14: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/shared/spin-up-the-stack/widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/run-container-common/kibana-fleet-data.asciidoc: line 4: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/run-container-common/{observability-docs-root}/docs/en/shared/open-kibana/widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/running-on-kubernetes-standalone.asciidoc: line 4: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/running-on-kubernetes-standalone.asciidoc: line 16: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/shared/spin-up-the-stack/widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/running-on-kubernetes-standalone.asciidoc: line 68: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/shared/open-kibana/widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/installation-layout.asciidoc: line 7: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/tab-widgets/install-layout-widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/uninstall-elastic-agent.asciidoc: line 11: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/tab-widgets/uninstall-widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/start-stop-elastic-agent.asciidoc: line 13: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/tab-widgets/start-widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/start-stop-elastic-agent.asciidoc: line 22: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/{observability-docs-root}/docs/en/ingest-management/tab-widgets/stop-widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/elastic-agent-configuration.asciidoc: line 4: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/create-standalone-agent-policy.asciidoc: line 4: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/inputs/input-configuration.asciidoc: line 4: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/inputs/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/outputs/output-configuration.asciidoc: line 8: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/outputs/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/outputs/output-elasticsearch.asciidoc: line 10: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/outputs/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/outputs/output-logstash.asciidoc: line 10: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/outputs/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc: line 8: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc: line 92: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/{observability-docs-root}/docs/en/ingest-management/tab-widgets/logging-widget.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/elastic-agent-standalone-features.asciidoc: line 8: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: elastic-agent/configuration/elastic-agent-monitoring.asciidoc: line 8: include file not found: /doc/ingest-docs/docs/en/ingest-management/elastic-agent/configuration/{observability-docs-root}/docs/en/ingest-management/standalone-note.asciidoc
INFO:build_docs:asciidoctor: ERROR: troubleshooting/troubleshooting.asciidoc: line 539: include file not found: /doc/ingest-docs/docs/en/ingest-management/troubleshooting/{observability-docs-root}/docs/en/ingest-management/tab-widgets/remove-endpoint-files/widget.asciidoc
```

**Comment by bmorelli25** [comment]
Doc build fixed. Command should be changed to:

```
$GIT_HOME/docs/build_docs --doc $GIT_HOME/ingest-docs/docs/en/ingest-management/index.asciidoc --resource=$GIT_HOME/apm-server/docs --resource=$GIT_HOME/observability-docs/docs --chunk 2
```

`conf.yaml` needs a new dependency on the observability guide

**Review by karenzone — APPROVED** [review]
This is uncharted territory for me, but the approach makes sense.  So what the heck! LGTM. Let's see what happens.

**Comment by bmorelli25** [comment]
Note that the broken CLA check is fine. Nothing is new here. All commits have already been checked against our CLA when they were initially committed to the observability-docs repo.

**Comment by bmorelli25** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|7.17|[](https://github.com/elastic/ingest-docs/pull/87)|
|✅|7.16|[](https://github.com/elastic/ingest-docs/pull/88)|
|✅|7.15|[](https://github.com/elastic/ingest-docs/pull/89)|
|✅|7.14|[](https://github.com/elastic/ingest-docs/pull/90)|
|✅|7.13|[](https://github.com/elastic/ingest-docs/pull/91)|
|✅|7.12|[](https://github.com/elastic/ingest-docs/pull/92)|
|❌|7.11|Conflict resolution was aborted by the user|

### Manual backport
To create the backport manually run:
```
backport --pr 78
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
