### PR TITLE
IngestArch: Add port numbers to ea-es architectures

### PR DESCRIPTION
**Pull request by karenzone**
Related: #197 

Updates Elastic Agent to Elasticsearch diagrams (2) with port numbers.  

**In this PR:** 
 - [ ] Elastic Agent to Elasticsearch: Agent installed
- [ ]  Elastic Agent to Elasticsearch: APIs for collection

### CODE REVIEW

**Comment by karenzone** [comment]
@nimarezainia Let's get these two diagrams fine tuned and merged. Any style changes we make will need to be reflected in all remaining diagrams. We can use these early iterations to get the look and content we want, and I'll carry that style throughout the remaining architectures. 

Screen Shot 2023-08-01 at 3 39 21 PM

Screen Shot 2023-08-01 at 3 39 03 PM

**Comment by nimarezainia** [comment]
@karenzone ports look good. Can I make some mods to the diagrams though (was going to open a separate issue, lmk if needed).

**(1)** In Both diagrams, the "Fleet" box should say "Fleet Server" and "Fleet" is a smaller box as a part of "Kibana"
**(2)** In the second diagram, the "External Infrastructure" that calls the API - should be on the right hand side of the picture and the API arrow should be pointing to  "Fleet" once the change in (1) above are made.

**Review by nimarezainia — APPROVED** [review]

**Comment by karenzone** [comment]
Thanks for the quick turn-around on this review, Nima. Absolutely we can make changes to the originals. Thank you for your clear description on what you want to see. I'll make it happen.

**Comment by karenzone** [comment]
43841

**Pull request merged**
