### PR TITLE
Update Integrations graphic on overview page

### PR DESCRIPTION
**Pull request by kilfoyle**
On the Agent & Fleet overview page, the [Integrations section](https://www.elastic.co/guide/en/fleet/master/fleet-overview.html#unified-integrations) shows an outdated graphic. In particular, "Endpoint Security" is now "Elastic Defend".

Closes: https://github.com/elastic/observability-docs/issues/2493

NEW VERSION
Screenshot 2023-04-12 at 6 16 26 PM

OLD VERSION
integrations old

### CODE REVIEW

**Review by karenzone — APPROVED** [review]
Thank you for picking this one up.  I noticed that the image size is different, but it looks good in the [preview](https://ingest-docs_97.docs-preview.app.elstc.co/guide/en/fleet/master/fleet-overview.html#unified-integrations).  So LGTM.

**Comment by kilfoyle** [comment]
Thanks @karenzone!
I'll keep this open for now as it'll be a good candidate to test the backport labels once they're ready.

**Comment by karenzone** [comment]
Thanks! The ingest architectures work is only in `main` so far with no need for backports. We'll definitely need backports now, and this will be a good test.

**Comment by kilfoyle** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.7|[](https://github.com/elastic/ingest-docs/pull/143)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by kilfoyle** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.6|[](https://github.com/elastic/ingest-docs/pull/144)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
