### PR TITLE
Fixed broken link to KSM sharding

### PR DESCRIPTION
**Pull request by alstolten**
Hi team, it seems the link moved, fixed it.

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]
LGTM! Thanks for fixing this @alstolten

Just one suggestion: We normally push changes to `main` and backport into the published release branches. After this one merges I will forward-port into the later branches so that the change doesn't get lost.

**Comment by alstolten** [comment]
Thank you @kilfoyle! I just hit the edit button from the docs page this time, and the rest I did what GH suggested to me. Anyway, what your wrote makes total sense, will check next time to PR to main.

**Comment by kilfoyle** [comment]
Just for reference, it looks like James already fixed this in 8.10 and main. :-) 
https://github.com/elastic/ingest-docs/pull/488

**Comment by alstolten** [comment]
Hmm, #488 does not seem to change anything with regards to `https://github.com/elastic/elastic-agent/blob/main/docs/elastic-agent-ksm-sharding.md` but I might miss sth.

**Comment by alstolten** [comment]
Perfect. Then we would just need to fix it for older versions.

**Comment by kilfoyle** [comment]
> Perfect. Then we would just need to fix it for older versions.

I've added backport labels for 8.8 and 8.7 so that should do the trick.

**Pull request merged**
