### PR TITLE
Fixed very small typo in air-gapped.asciidoc

### PR DESCRIPTION
**Pull request by frederikb96**
Typo fix: "om" replaced with "in"

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]
Nice. Thanks very much @frederikb96!
One request: It looks like for me to merge this PR you'd need to sign the contributor agreement (according to the CI check below). Would you mind doing that?

**Comment by frederikb96** [comment]
> Nice. Thanks very much @frederikb96! One request: It looks like for me to merge this PR you'd need to sign the contributor agreement (according to the "CLA" CI check below). Would you mind doing that? If you click on the "details" link I think it should take you to the agreement form.

Yes sure, I did that, but not sure if it will take some time to be updated here :)

**Comment by kilfoyle** [comment]
Looks like it passed. :-) 
Thanks again @frederikb96! I'll merge and backport this one later today or tomorrow.

**Comment by frederikb96** [comment]
> Looks like it passed. :-) 
> Thanks again @frederikb96! I'll merge and backport this one later today or tomorrow.

Perfect, happy to help with this tiny improvement 😄

**Comment by kilfoyle** [comment]
@elasticmachine run docs-build

**Pull request merged**
